name       : voikko-fi
version    : '2.2'
release    : 2
source     :
    - http://www.puimula.org/voikko-sources/voikko-fi/voikko-fi-2.2.tar.gz : fd5e730bb79b65d57d1382252e3b1c7ea43794dc6967668e7dd7e1cbbe4d845d
license    : GPL-2.0
component  : office
summary    : Voikko-fi (previously know as Suomi-malaga) is a description of Finnish morphology written for libvoikko.
description: |
    Voikko-fi (previously know as Suomi-malaga) is a description of Finnish morphology written for libvoikko.
builddeps  :
    - pkgconfig(libvoikko)
    - foma-devel
rundeps    :
    - foma
    - libvoikko
build      : |
    %make vvfst
install    : |
    %make DESTDIR="$installdir/usr/share/voikko/" vvfst-install
