name       : voikko-fi
version    : 2.1
release    : 1
source     :
    - http://www.puimula.org/voikko-sources/voikko-fi/voikko-fi-2.1.tar.gz : 71a823120a35ade6f20eaa7d00db27ec7355aa46a45a5b1a4a1f687a42134496
license    : GPL-2.0
component  : office
summary    : Voikko-fi (previously know as Suomi-malaga) is a description of Finnish morphology written for libvoikko.
description: |
    Voikko-fi (previously know as Suomi-malaga) is a description of Finnish morphology written for libvoikko.
builddeps  :
    - pkgconfig(libvoikko)
    - foma-devel
rundeps    :
    - foma
    - libvoikko
build      : |
    %make vvfst
install    : |
    %make DESTDIR="$installdir/usr/share/voikko/" vvfst-install
